on:
  schedule:
    - cron: '5 5  * * *'
  workflow_dispatch:

name: schedule
jobs:
  ops-main:
    if: github.repository == 'pkp/ops'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.2
            validate: 'validate'
            database: pgsql
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_3_0,stable-3_4_0,stable-3_5_0'
          - php-version: 8.2
            validate: 'validate'
            database: mariadb
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_4_0,stable-3_5_0'
          - php-version: 8.2
            validate: 'validate'
            database: mysql
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_3_0,stable-3_4_0,stable-3_5_0'
    name: ops-main
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
          node_version: 20
          dataset_branch: 'main'
          DATASETS_ACCESS_KEY:  ${{secrets.DATASETS_ACCESS_KEY}}
          DEBUG_IN_TMATE: false

  ops-stable-3_5_0:
    if: github.repository == 'pkp/ops'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.2
            validate: 'validate'
            database: pgsql
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_3_0,stable-3_4_0'
          - php-version: 8.2
            database: mariadb
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_4_0'
          - php-version: 8.2
            validate: 'validate'
            database: mysql
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_3_0,stable-3_4_0'
    name: ops-stable-3_5_0
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
          node_version: 16
          dataset_branch: 'stable-3_5_0'
          DATASETS_ACCESS_KEY: ${{secrets.DATASETS_ACCESS_KEY}}
          DEBUG_IN_TMATE: false

  ops-stable-3_4_0:
    if: github.repository == 'pkp/ops'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 8.1
            validate: 'validate'
            database: pgsql
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_3_0'
          - php-version: 8.1
            database: mariadb
            test: 'test'
            SAVE_BUILD: 'save_build'
          - php-version: 8.1
            validate: 'validate'
            database: mysql
            test: 'test'
            SAVE_BUILD: 'save_build'
            upgrade: 'upgrade'
            upgrade_test: 'stable-3_3_0'
    name: ops-stable-3_4_0
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
          node_version: 16
          dataset_branch: 'stable-3_4_0'
          DATASETS_ACCESS_KEY: ${{secrets.DATASETS_ACCESS_KEY}}
          DEBUG_IN_TMATE: false

  ops-stable-3_3_0:
    if: github.repository == 'pkp/ops'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-version: 7.4
            validate: 'validate'
            database: pgsql
            test: 'test'
            SAVE_BUILD: 'save_build'
          - php-version: 7.4
            database: mysql
            test: 'test'
            SAVE_BUILD: 'save_build'

    name: ops-stable-3_3_0
    steps:
      - uses: pkp/pkp-github-actions@v1
        with:
          node_version: 12
          dataset_branch: 'stable-3_3_0'
          DATASETS_ACCESS_KEY: ${{secrets.DATASETS_ACCESS_KEY}}
          DEBUG_IN_TMATE: false
